export const PRODUCTS_READ_START = "PRODUCTS_READ_START";
export const PRODUCTS_READ_OK = "PRODUCTS_READ_OK";
export const PRODUCTS_READ_ERROR = "PRODUCTS_READ_ERROR";

export const PRODUCTS_CREATE_START = "PRODUCTS_CREATE_START";
export const PRODUCTS_CREATE_OK = "PRODUCTS_CREATE_OK";
export const PRODUCTS_CREATE_ERROR = "PRODUCTS_CREATE_ERROR";

export const PRODUCTS_EDIT_START = "PRODUCTS_EDIT_START";
export const PRODUCTS_EDIT_OK = "PRODUCTS_EDIT_OK";
export const PRODUCTS_EDIT_ERROR = "PRODUCTS_EDIT_ERROR";

export const PRODUCTS_DELETE_START = "PRODUCTS_DELETE_START";
export const PRODUCTS_DELETE_OK = "PRODUCTS_DELETE_OK";
export const PRODUCTS_DELETE_ERROR = "PRODUCTS_DELETE_ERROR";
