import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import { productsReadAction, productsCreateAction } from "../store/actions";
import { Product } from "../store/products/interface";

const Home: NextPage = () => {
  const dispatch = useDispatch();

  const products = useSelector((state: any) => state.products);

  console.log("products", products);

  useEffect(() => {
    dispatch(productsReadAction());
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Productos</h1>
      <ul>
        {products.data.map((p: Product) => (
          <li key={p.id}>{p.name}</li>
        ))}
      </ul>
    </div>
  );
};

export default Home;
