export const AUTH_CREATE_USER_START = "AUTH_CREATE_USER_START";
export const AUTH_CREATE_USER_OK = "AUTH_CREATE_USER_OK";
export const AUTH_CREATE_USER_ERROR = "AUTH_CREATE_USER_ERROR";

export const AUTH_LOGIN_START = "AUTH_LOGIN_START";
export const AUTH_LOGIN_OK = "AUTH_LOGIN_OK";
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";

export const AUTH_LOGOUT_START = "AUTH_LOGOUT_START";
export const AUTH_LOGOUT_OK = "AUTH_LOGOUT_OK";
export const AUTH_LOGOUT_ERROR = "AUTH_LOGOUT_ERROR";
